# This is a basic workflow to help you get started with Actions

name: Python_Automation

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Run the action
        uses: potatoqualitee/mssqlsuite@v1.7
        with:
          install: sqlengine, sqlpackage

      - name: Run sqlclient
        run: sqlcmd -S localhost -U sa -P dbatools.I0 -d tempdb -Q "SELECT @@version;"
      # # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # - uses: actions/checkout@v3
      # - name: Install dependencies
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install sqlalchemy
      #     pip install pyodbc

      # # Runs a single command using the runners shell
      # - name: Run Sample Python Script
      #   run: python .github/workflows/DDL_POC.py
